### ISSUE TITLE
QuickLook plugin is incompatible with AppCode 2016.1 (former 3.4)

### ISSUE THREAD

**Issue by TatyanaShabaeva** [JustSid/AppCode-QuickLook#3]
Related issue in JetBrains tracker: https://youtrack.jetbrains.com/issue/OC-13141

**Comment by JustSid** [comment]
I was (foolishly) waiting for the final release to see if there were any further API breakage. I've just published a new version that fixes the crash and will update the plugin during EAPs from now on.
